Improve UI
slavo3dev/ourhealthyday pull request #18
Opened 2023-08-24 14:24 UTC by kulisic4

Improving UI, completely redesigned Home and Blog feature.

2023-08-26 20:41 UTC, nikolaklenje requested changes

2023-08-26 20:41 UTC, nikolaklenje commented on component/Counter/index.tsx
> +	};
For smaller functions that you not reuse in other parts of code you can always write them inline (inside of the tag 
and have fewer lines of code)

2023-08-26 20:41 UTC, nikolaklenje commented on component/Fact/index.tsx
>  				</a>
Use Link from NextJs and find out what are advantages of using it.

2023-08-26 20:41 UTC, nikolaklenje commented on component/Post/index.tsx
> +	}, []);
Do not use empty dependency in useEffect. Find another way

2023-08-26 20:41 UTC, nikolaklenje commented on component/PostCard/index.tsx
> +	}, []);
Do not use empty dependency

2023-08-26 20:41 UTC, nikolaklenje commented on component/PostCard/index.tsx
> +		}
Too many repetitions

2023-08-26 20:41 UTC, nikolaklenje commented on component/StoreItems/index.tsx
> +							<p className="px-5 md:px-20 py-5 md:py-20">
Again white spaces

2023-08-26 20:41 UTC, nikolaklenje commented on component/StoreItems/index.tsx
> +							<img className="h-full border-2 border-teal-500 rounded-lg" src="https://cdn.outsideonline.com/wp-content/uploads/2022/10/somos-smoky-chipotle_h.jpg?width=730" />
Again Image

2023-08-26 20:41 UTC, nikolaklenje commented on lib/constants/index.ts
>  ];
Too many repetitions.

2023-12-03 02:45 UTC, slavo3dev approved these changes

2023-12-03 02:45 UTC, merged